---
- name: starting process
  hosts: localhost
  become_user: root
  vars:
    - service_name: apache2
    - type: restarted
 
  tasks:
   - name: To start process
     service:
       name: "{{ service_name }}"
       state: "{{ type }}"
