---
- name: starting process
  hosts: localhost
  gather_facts: no
  vars:
    - service_name: ngnix
    - type: restarted
 
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Restart Nginx
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ type }}"
