---
- name: Create a new itsm incident
  hosts: localhost
  vars:
    ansible_python_interpreter: ~/servicenow-env/bin/python
  environment:
    ANSIBLE_COLLECTIONS_PATHS: /usr/share/ansible/collections
  tasks:
  - name: Create an Incident
    servicenow.servicenow.snow_record:
      username: admin
      password: 7fbhrN8^ED*B
      instance: dev193710
      state: present
      data:
        short_description: "Apache service is not running"
        severity: 3
        priority: 2
    register: new_incident
  - name: Display incident details
    debug:
      msg: "{{ new_incident }}"
