---
- name: starting process
  hosts: localhost
  become_user: root
  become_method: sudo
  vars:
    - service_name: ngnix
    - type: restarted
 
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes
    - name: Restart Nginx
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ type }}"
