- name: Ensure Apache is running
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure apache2 is installed
      ansible.builtin.apt:
        name: apache2
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2 is installed
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Restart Apache service
      ansible.builtin.service:
        name: apache2
        state: restarted
