---
- name: starting process
  hosts: localhost
  become_user: root
  vars:
    - service_name: ngnix
    - type: restarted
 
  tasks:
    - name: Restart Nginx
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ type }}"
