---
- name: starting process
  hosts: localhost
  become_user: root
  vars:
    - service_name: httpd
    - type: started
 
  tasks:
   - name: To start process
     service:
       name: "{{ service_name }}"
       state: "{{ type }}"
     register: process
