---
- name: Create new Incident
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Create an Incident
      servicenow.itsm.incident:
        username: admin
        password: 7fbhrN8^ED*B
        instance: dev193710
        state: new
        data:
          short_description: "Apache service is not running"
          severity: 3
          priority: 2
      register: new_incident
    - name: Display incident details
      debug:
        msg: "{{ new_incident }}"
