---
- name: Create a new ITSM incident
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow
      # vars:
    # ansible_python_interpreter: /root/servicenow-env/lib/python  # Ensure this is the correct path
  environment:
    ANSIBLE_COLLECTIONS_PATHS: /usr/share/ansible/collections/ansible_collections:~/.ansible/collections/ansible_collections/
  tasks:
    - name: Install pysnow library
      pip:
        name:
          - pysnow
          - packaging
        executable: /root/servicenow-env/bin/pip
    - name: Install ServiceNow collection
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install servicenow.servicenow
      delegate_to: localhost
 
    - name: Queue build of a project in Jenkins
      ansible.builtin.uri:
        url: https://dev193710.service-now.com/api/now/table/incident
        user: admin
        password: 7fbhrN8^ED*B
        method: POST
        force_basic_auth: true
        status_code: 201
        headers:
          Content-Type: application/json
        body: |
          {
          "short_description": "Apache server is not running",
          "Priority": "2"
          }     
            # - name: Create an Incident
            #  snow_record:
            #  username: admin
            # password: 7fbhrN8^ED*B
            # instance: dev193710
          # state: present
          #  data:
       # short_description: "Apache service is not running"
        #  severity: 3
          # priority: 2
      register: new_incident
    - name: Display incident details
      debug:
        msg: "{{ new_incident }}"
