- name: Ensure Apache is running
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure apache2 is installed
      ansible.builtin.apt:
        name: apache2
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2 is installed
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Restart Apache service
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: Create an incident
      servicenow.servicenow.snow_record:
        username: admin
        password: 7fbhrN8^ED*B
        instance: dev193710
        state: present
        data:
          short_description: "Apache service is not running"
          severity: 3
          priority: 2
        register: new_incident
    - name: Display inc details
      debug:
        msg: "{{ new_incident }}"
