- name: Ensure Apache is running
  hosts: all
  become: yes
  tasks:
    - name: Ensure apache2 is installed
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'
 
    - name: Restart Apache service
      ansible.builtin.service:
        name: "{{ ansible_os_family == 'Debian' | ternary('apache2', 'httpd') }}"
        state: restarted
