- name: Ensure Apache is running
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure apache2.4 is installed
      wait_for_connection:
        timeout: 30
      win_service:
        name: apache2.4
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache2.4
        state: present
    - name: Restart Apache service
      win_service:
        name: apache2.4
        state: restarted
