- name: Ensure Apache is running
  hosts: 172.31.87.46
  become: true
  gather_facts: no
  tasks:
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache2.4
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache2.4
        state: present
    - name: Restart Apache service
      win_service:
        name: apache2.4
        state: restarted
