- name: Ensure Apache is running
  hosts: 18.212.49.181
  become: true
  tasks:
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache2.4
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache2.4
        state: present
    - name: Restart Apache service
      win_service:
        name: apache2.4
        state: restarted
