- name: Ensure Apache is running
  hosts: all
  become: yes
  ansible_connection: winrm
  ansible_port: 5082
  gather_facts: no
  tasks:
    - name: Ensure apache2.4 is installed
      ansible.windows.win_service:
        name: apache
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      ansible.windows.win_service:
        name: apache
        state: present
    - name: Restart Apache service
      ansible.windows.win_service:
        name: apache
        state: restarted
