---
- name: Ensure Apache is running
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Start Apache if it's not running
      win_service:
        name: Apache2.4
        state: started
      when: apache_status.status != 'Running'
 
    - name: Restart Apache service (only if needed)
      win_service:
        name: Apache2.4
        state: restarted
      when: apache_status.status == 'Running'
