---
- name: Start Apache Service on Windows using PowerShell
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Start Apache service using PowerShell
      win_shell: |
        Start-Service -Name "Apache2.4"
