- name: Ensure Apache is running
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure apache2.4 is installed
      ansible.windows.win_service:
        name: apache2
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      ansible.windows.win_service:
        name: apache2
        state: present
    - name: Restart Apache service
      ansible.windows.win_service:
        name: apache2
        state: restarted
