- name: Ensure Apache is running
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Restart Apache service
      win_service:
        name: Apache2.4
        start_mode: auto
        state: restarted
