- name: Ensure Apache is running
  hosts: all
  ansible_port: 5985
  ansible_winrm_transport: basic
  gather_facts: no
  tasks:
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache
        state: absent
     # when: ansible_os_family == 'Debian'
    - name: Ensure apache2.4 is installed
      win_service:
        name: apache
        state: present
    - name: Restart Apache service
      win_service:
        name: apache
        state: restarted
